- hosts: vm1
  become: yes

  vars_prompt:
    - name: vault_ldap_username
      prompt: "Enter UT username"
      private: false

    - name: vault_ldap_password
      prompt: "Enter UT password"
      private: true

  vars:
    vm_name: "c11483vm"
    domain: "{{ vm_name }}.sysadm.ee"
    inventory_domain: "inventory.{{ vm_name }}.sysadm.ee"
    blog_domain: "blog.{{ vm_name }}.sysadm.ee"
    inventory_token: "845e6732f32b81dd778972703474ccbb"
    vm_public_ip: "172.17.90.60"

  roles:
    - role: etais
    - role: week04_web
      tags: week04_web
    - role: week05_dns
      tags: week05_dns
    - role: week06_email
      tags: week06_email
    - role: week07_tls
      tags: week07_tls
    - role: week08_filesystems
      tags: week08_filesystems
    - role: week09_containers
      tags: week09_containers
    - role: week10_devops
      tags: week10_devops
    - role: week11_monitoring
      tags: week11_monitoring
