---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart inventory-api
  ansible.builtin.systemd:
    name: "{{ inventory_service }}"
    state: restarted
    daemon_reload: true

- name: reload nfs exports
  ansible.builtin.command: exportfs -ra

- name: restart nfs-server
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted

- name: restart smb
  ansible.builtin.systemd:
    name: smb
    state: restarted

- name: restart nmb
  ansible.builtin.systemd:
    name: nmb
    state: restarted

- name: restorecon data
  ansible.builtin.command: restorecon -Rv /data

- name: restorecon samba
  ansible.builtin.command: restorecon -Rv "{{ samba_share_dir }}"
