---
- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted

- name: restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted
