---
- name: restart httpd
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
  failed_when: false

- name: restart dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: restarted
